### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by MartinBoehm1** [rstropek/htl-mobile-computing#77]

**Comment by rstropek** [comment]
Hi @MartinBoehm1!

I am a little bit confused. You created the issue and closed it again. However, I took a look at the links you provided. Nearly solved. Try to fix the following issues:

* Don't use untyped members in *app.component.ts* (e.g. line 9)
* The *Calc Tower* button is not disabled if the user enters an invalid value.

Greetings,
Rainer Stropek.
