### ISSUE TITLE
M1ztl Homework

### ISSUE THREAD

**Issue by M1ztl** [rstropek/htl-mobile-computing#79]
Turmrechnen example link.
https://stackblitz.com/edit/angular-umeywv
Lukas Mistlberger, 4BHIF

**Comment by rstropek** [comment]
Hi @M1ztl!

Thank you for your link. It works but it does not yet fulfill the specification. Fix the following issues and the extra point will be yours:

* Disable the *calculate* button in case of invalid input (tip: `[disabled]...` binding)
* Display the error immediately, not only after the user pressed *calculate*
* Tip: Avoid untyped variables and arrays (e.g. `res`)

Greetings,
Rainer Stropek.
