### ISSUE TITLE
tklecka Homework

### ISSUE THREAD

**Issue by tklecka** [rstropek/htl-mobile-computing#80]
4BHIF Klecka Tim  
[https://stackblitz.com/edit/angular-kcrejq](url)

**Comment by rstropek** [comment]
Hi @tklecka!

Thank you for the link. Very nice styling 👍, and it works as expected. The extra point is yours. Tip: Avoid untyped arrays (e.g. `resultArray`).

Greetings,
Rainer Stropek.
