### ISSUE TITLE
Turmrechnen Bsp:

### ISSUE THREAD

**Issue by xxANONYMxx** [rstropek/htl-mobile-computing#81]
https://stackblitz.com/edit/angular-bmnahd

**Comment by rstropek** [comment]
Hi @xxANONYMxx!

Thank you for the link. It is nearly as expected. Correct the following few bugs and the extra point will be yours:

* If the input is invalid (i.e. height < 2), the *calculate* button has to be disabled
* The error should be displayed immediately, not only after clicking *calculate*
* And a final tip: Use `type="number"` for numeric inputs

Greetings,
Rainer Stropek
