### ISSUE TITLE
Turmrechnen

### ISSUE THREAD

**Issue by noahmaiss09** [rstropek/htl-mobile-computing#82]
https://angular-7jj2fj.stackblitz.io

**Comment by rstropek** [comment]
Hi @noahmaiss09!

Nearly. The only thing that is missing is disabling the *calculate* button if input is invalid (height < 2). Tip: Use a `[disabled]=...` binding. Send me a link to an updates version of your program and the extra point will be yours.

Greetings,
Rainer Stropek.
