### ISSUE TITLE
Turmrechnen

### ISSUE THREAD

**Issue by JonaMaiss** [rstropek/htl-mobile-computing#83]
https://angular-nkqdsc.stackblitz.io
https://stackblitz.com/edit/angular-nkqdsc

**Comment by rstropek** [comment]
Hi @JonaMaiss!

Thank you for your link. Unfortunately, the calculation logic does not work yet. If you need help, feel free to send questions or ask questions when we have our next lessons.

Greetings,
Rainer Stropek.
