### ISSUE TITLE
michaelhitzker Homework

### ISSUE THREAD

**Issue by michaelhitzker** [rstropek/htl-mobile-computing#85]
Link to the Turmrechnen-Homework
https://stackblitz.com/edit/turmrechnen-michaelhitzker
Michael Hitzker, 4BHIF

**Comment by rstropek** [comment]
Hi @michaelhitzker!

Thank you for your link. Works as expected 👍. The extra point is yours. Just one tip: Avoid untyped arrays (e.g. `turm`).

Greetings,
Rainer Stropek
