### ISSUE TITLE
Turmrechnen HÜ

### ISSUE THREAD

**Issue by Lauch** [rstropek/htl-mobile-computing#87]
Hier ist der Link zu meinem Turmrechnen Beispiel:
https://stackblitz.com/edit/angular-lu51i1

**Comment by rstropek** [comment]
Hi @Lauch!

Nearly. Your solution does not fully implement the specification. The *calculate* button should be disabled if height is lower than 2. Additionally, the error message should appear immediately, not after clicking *calculate*. Fix that and the extra point will be yours.

Greetings,
Rainer Stropek.
