### ISSUE TITLE
Turmrechnen HÜ

### ISSUE THREAD

**Issue by AndreasKastenhofer** [rstropek/htl-mobile-computing#89]
https://stackblitz.com/edit/angular-6xwjsx

**Comment by rstropek** [comment]
Hi @AndreasKastenhofer!

Thank you for your link. The extra point is yours. Just one tip: You algorithm does not work correctly if you run *Calculate* multiple times. E.g. run it with height 5 and then with height 2. The result is not correctly purged before displaying the new result.

Greetings,
Rainer Stropek.
