### ISSUE TITLE
Turmrechnen Homework

### ISSUE THREAD

**Issue by Staniel99** [rstropek/htl-mobile-computing#92]
https://stackblitz.com/edit/angular-bvgqzp
Stefan Daniel, 4BHIF

**Comment by rstropek** [comment]
Hi @Staniel99!

Thank you for your link. Works as expected. Two tips:

* Use `type="number"` for numeric inputs
* Avoid untyped arrays like `res`

The extra point is yours.

Greetings,
Rainer Stropek.
