### ISSUE TITLE
Link to Responsive Calculator

### ISSUE THREAD

**Issue by michaelhitzker** [rstropek/htl-mobile-computing#96]
Dear Mr. Stropek!

The link to my GitHub Repo: https://github.com/michaelhitzker/responsive-calculator-michaelhitzker
The link to the hosted calculator: https://michaelhitzker.com/htl/responsive-calculator/

**Comment by rstropek** [comment]
Great 👍, an extra point is yours.

Greetings,
Rainer Stropek.
